apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "llama-cpp.fullname" . }}-models
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llama-cpp.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.model.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.model.pvc.size }}
  {{- if .Values.model.pvc.storageClass }}
  storageClassName: {{ .Values.model.pvc.storageClass }}
  {{- end }}
