apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llama-cpp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llama-cpp.labels" . | nindent 4 }}
automountServiceAccountToken: true
